on:
  schedule:
    # Run daily job at 8:00 PM PT
    - cron: '0 3 * * *'

name: clippybot

jobs:
  clippy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install rust toolchain
        id: toolchain
        run: |
          rustup toolchain install stable --profile minimal --component clippy
          rustup override set stable

      - uses: camshaft/rust-cache@v1

      - name: Run cargo clippy on main crates
        run: |
          # deriving Eq may break API compatibility so we disable it
          # See https://github.com/rust-lang/rust-clippy/issues/9063
          #
          # manual_clamp will panic when min > max
          # See https://github.com/rust-lang/rust-clippy/pull/10101
          cargo clippy --fix --all-features --all-targets --workspace -- -A clippy::derive_partial_eq_without_eq -A clippy::manual_clamp -D warnings

      - name: Run clippy on dc/wireshark crate
        working-directory: dc/wireshark
        run: cargo clippy --fix --allow-dirty --tests

      - name: Run clippy on all examples crates
        working-directory: examples
        run: cargo clippy --all-features --all-targets --fix --allow-dirty -- -A clippy::manual_clamp -A clippy::uninlined_format_args -D warnings

      - name: Run clippy on tools/xdp crate
        working-directory: tools/xdp
        run: cargo clippy --fix --allow-dirty

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7

